import AVFoundation
import AudioToolbox
import Combine
import Foundation

enum ADASAudioMode:String,CaseIterable,Identifiable{case beepOnly,allWarnings;var id:String{rawValue};var title:String{self == .beepOnly ? "Chỉ tiếng bip":"Tất cả cảnh báo"}}
final class ADASWarningManager:NSObject,ObservableObject,AVAudioPlayerDelegate,AVSpeechSynthesizerDelegate{
 static let volumeKey="xadas.warning.volume",vibrationKey="xadas.warning.vibration",audioModeKey="xadas.warning.audioMode";static let minimumDistanceAlertSpeedKPH=60.0
 private var player:AVAudioPlayer?;private let speechSynthesizer=AVSpeechSynthesizer();private var lastDistanceAlertAt:TimeInterval=0,lastLaneAlertAt:TimeInterval=0,lastOverspeedAlertAt:TimeInterval=0,lastSpeechAt:TimeInterval=0,lastLeadStartAlertAt:TimeInterval=0;private var lastSpokenKey="";private var lastDistanceRisk:LeadDistanceRisk = .unavailable;private var lastLaneState:LaneDepartureState = .unavailable;private var lastTrafficSignUpdatedAt:TimeInterval=0;private var lastTrafficSign:TrafficSignKind?;private var stoppedLeadBaselineMeters:Double?,stoppedLeadArmedAt:TimeInterval=0,stoppedLeadLastSeenAt:TimeInterval=0;private var stoppedLeadMoveFrames=0,wasStoppedWithLead=false;private var ownsPlaybackSession=false
 override init(){super.init();UserDefaults.standard.register(defaults:[Self.volumeKey:0.35,Self.vibrationKey:true,Self.audioModeKey:ADASAudioMode.allWarnings.rawValue]);player=try? AVAudioPlayer(data:Self.makeBeepWAV());player?.delegate=self;player?.prepareToPlay();speechSynthesizer.delegate=self}
 private var warningVolume:Float{Float(min(max(UserDefaults.standard.double(forKey:Self.volumeKey),0),1))};private var vibrationEnabled:Bool{UserDefaults.standard.bool(forKey:Self.vibrationKey)};private var audioMode:ADASAudioMode{ADASAudioMode(rawValue:UserDefaults.standard.string(forKey:Self.audioModeKey) ?? "") ?? .allWarnings}
 func update(distance:LeadDistanceState,lane:LaneDepartureState,trafficSign:TrafficSignState,vehicleSpeedKPH:Double){announceNewTrafficSignIfNeeded(trafficSign);let now=ProcessInfo.processInfo.systemUptime;updateLeadVehicleStart(distance:distance.distanceMeters,vehicleSpeedKPH:vehicleSpeedKPH,now:now);let lw=lane == .warningLeft || lane == .warningRight,plw=lastLaneState == .warningLeft || lastLaneState == .warningRight;if lw && (!plw || lane != lastLaneState || now-lastLaneAlertAt>=3){let left=lane == .warningLeft;alert(strong:false,message:left ? "Cảnh báo lệch làn trái":"Cảnh báo lệch làn phải",key:left ? "lane-left":"lane-right");lastLaneAlertAt=now};lastLaneState=lane;let mapLimit=UserDefaults.standard.object(forKey:MapSpeedLimitProvider.currentLimitKey) as? Int;if let limit=mapLimit,vehicleSpeedKPH>=Double(limit)+5,now-lastOverspeedAlertAt>=6{alert(strong:true,message:"Cảnh báo quá tốc độ. Giới hạn \(limit) ki lô mét một giờ",key:"overspeed-map-\(limit)");lastOverspeedAlertAt=now};guard vehicleSpeedKPH>Self.minimumDistanceAlertSpeedKPH else{lastDistanceRisk = .unavailable;return};let danger=distance.risk == .danger && (lastDistanceRisk != .danger || now-lastDistanceAlertAt>=2),caution=distance.risk == .caution && lastDistanceRisk != .caution && now-lastDistanceAlertAt>=1.2;if danger{alert(strong:true,message:"Cảnh báo, khoảng cách quá gần",key:"distance-danger");lastDistanceAlertAt=now}else if caution{alert(strong:false,message:"Chú ý khoảng cách",key:"distance-caution");lastDistanceAlertAt=now};lastDistanceRisk=distance.risk}
 private func updateLeadVehicleStart(distance:Double?,vehicleSpeedKPH:Double,now:TimeInterval){guard vehicleSpeedKPH<=2 else{resetStoppedLead();return};if let distance,distance>=1.5,distance<=35{stoppedLeadLastSeenAt=now;if stoppedLeadBaselineMeters==nil{stoppedLeadBaselineMeters=distance;stoppedLeadArmedAt=now;stoppedLeadMoveFrames=0;wasStoppedWithLead=true;return};if now-stoppedLeadArmedAt>=1.2,let baseline=stoppedLeadBaselineMeters{let moved=distance-baseline>=max(1.2,baseline*0.10);stoppedLeadMoveFrames=moved ? stoppedLeadMoveFrames+1:max(0,stoppedLeadMoveFrames-1);if stoppedLeadMoveFrames>=2{fireLeadVehicleStart(now:now)}}}else if wasStoppedWithLead,stoppedLeadArmedAt>0,now-stoppedLeadArmedAt>=1.2,now-stoppedLeadLastSeenAt>=0.55,now-stoppedLeadLastSeenAt<=2.5{fireLeadVehicleStart(now:now)}}
 private func fireLeadVehicleStart(now:TimeInterval){guard now-lastLeadStartAlertAt>=5 else{return};alert(strong:false,message:"Xe phía trước đã di chuyển",key:"lead-vehicle-start",forceSpeech:true);lastLeadStartAlertAt=now;resetStoppedLead()};private func resetStoppedLead(){stoppedLeadBaselineMeters=nil;stoppedLeadArmedAt=0;stoppedLeadLastSeenAt=0;stoppedLeadMoveFrames=0;wasStoppedWithLead=false}
 private func announceNewTrafficSignIfNeeded(_ state:TrafficSignState){guard state.updatedAt>0,state.updatedAt != lastTrafficSignUpdatedAt,let sign=state.lastConfirmedSign else{return};lastTrafficSignUpdatedAt=state.updatedAt;guard sign != lastTrafficSign else{return};lastTrafficSign=sign;switch sign{case .speedLimit(let v):alert(strong:false,message:"Giới hạn tốc độ \(v) ki lô mét một giờ",key:"sign-limit-\(v)",forceSpeech:true);case .denseAreaStart:alert(strong:false,message:"Bắt đầu khu đông dân cư",key:"sign-dense-start",forceSpeech:true);case .denseAreaEnd:alert(strong:false,message:"Hết khu đông dân cư",key:"sign-dense-end",forceSpeech:true)}}
 func testWarning(){alert(strong:true,message:"Hệ thống cảnh báo hoạt động",key:"test",forceSpeech:true)}
 private func alert(strong:Bool,message:String,key:String,forceSpeech:Bool=false){if !ownsPlaybackSession{IvyAudioSessionManager.shared.beginPlayback();ownsPlaybackSession=true};let volume=warningVolume;player?.currentTime=0;player?.volume=strong ? min(volume*1.15,1):volume;player?.play();if vibrationEnabled{AudioServicesPlaySystemSound(kSystemSoundID_Vibrate)};guard audioMode == .allWarnings else{return};let now=ProcessInfo.processInfo.systemUptime;guard forceSpeech || key != lastSpokenKey || now-lastSpeechAt>=5 else{return};if speechSynthesizer.isSpeaking{speechSynthesizer.stopSpeaking(at:.immediate)};let u=AVSpeechUtterance(string:message);u.voice=AVSpeechSynthesisVoice(language:"vi-VN");u.rate=0.50;u.volume=volume;speechSynthesizer.speak(u);lastSpokenKey=key;lastSpeechAt=now}
 private func releaseWarningAudioIfIdle(){guard player?.isPlaying != true,!speechSynthesizer.isSpeaking,ownsPlaybackSession else{return};ownsPlaybackSession=false;IvyAudioSessionManager.shared.endPlayback()};func audioPlayerDidFinishPlaying(_ player:AVAudioPlayer,successfully flag:Bool){releaseWarningAudioIfIdle()};func speechSynthesizer(_ synthesizer:AVSpeechSynthesizer,didFinish utterance:AVSpeechUtterance){releaseWarningAudioIfIdle()};func speechSynthesizer(_ synthesizer:AVSpeechSynthesizer,didCancel utterance:AVSpeechUtterance){releaseWarningAudioIfIdle()}
 private static func makeBeepWAV()->Data{let sr=22_050,d=0.18,f=880.0,c=Int(Double(sr)*d);var pcm=Data(capacity:c*2);for i in 0..<c{let t=Double(i)/Double(sr),fade=min(1.0,min(t/0.02,(d-t)/0.04)),s=sin(2 * .pi * f * t)*0.32*max(0,fade);var v=Int16(max(-1,min(1,s))*Double(Int16.max)).littleEndian;withUnsafeBytes(of:&v){pcm.append(contentsOf:$0)}};var data=Data();func a(_ s:String){data.append(s.data(using:.ascii)!)};func u32(_ x:UInt32){var v=x.littleEndian;withUnsafeBytes(of:&v){data.append(contentsOf:$0)}};func u16(_ x:UInt16){var v=x.littleEndian;withUnsafeBytes(of:&v){data.append(contentsOf:$0)}};a("RIFF");u32(UInt32(36+pcm.count));a("WAVE");a("fmt ");u32(16);u16(1);u16(1);u32(UInt32(sr));u32(UInt32(sr*2));u16(2);u16(16);a("data");u32(UInt32(pcm.count));data.append(pcm);return data}
}
